---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deploymentName }}
  labels:
    app: {{ .Values.deploymentName }}
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.deploymentName }}
  template:
    metadata:
      labels:
        app: {{ .Values.deploymentName }}
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      containers:
        - name: app
          image: {{ .Values.imageName }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          volumeMounts:
            - name: 'password-token'
              mountPath: '/mnt/secrets-store'
              readOnly: true
      volumes:
        - name: password-token
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: password-token