---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccountName }}
  namespace: monitoring
  labels:
    app: {{ .Values.portfoliWebAppName }}
  annotations:
    {{- toYaml .Values.annotations | nindent 4 }}